### ISSUE TITLE
ODS proj_news_viz

### ISSUE THREAD

**Issue by kuk** [natasha/corus#25]
https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/Available-datasets

**Comment by kuk** [comment]
@monuvio @vtrokhymenko нашёл ваши контакты на https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/Available-datasets/_history . Есть ли возможность использовать датасеты ods-ai-ml4sg вне вашего проекта?

При скачивании получаю ошибку `AccessDeniedException: 403 There is an account problem for the requested project`
```
> pip install gsutil
> gsutil config
This command will create a boto config file at /XXXX
containing your credentials, based on your responses to the following
questions.
Please navigate your browser to the following URL:
XXXX
in your browser you should see a page that requests you to authorize access to Google Cloud Platform APIs and Services on your behalf. After you approve, an authorization code will be displayed.

Enter the authorization code: XXXX
Please navigate your browser to https://cloud.google.com/console#/project,
then find the project you will use, and copy the Project ID string from the
second column. Older projects do not have Project ID strings. For such projects,
 click the project and then copy the Project Number listed under that project.

What is your project-id? neat-coast-248415

gsutil developers rely on user feedback to make improvements to the
tool. Would you like to send anonymous usage statistics to help
improve gsutil? [y/N] y

Boto config file "/XXXX" created. If you need to use a
proxy to access the Internet please see the instructions in that file.
> gsutil cp gs://proj_news_viz/gazeta.csv .
AccessDeniedException: 403 There is an account problem for the requested project.
```

Мы тут коллекционируем размеченные и сырые тексты на русском языке. Сейчас накопилось ~10Гб текстов новостной тематики https://github.com/natasha/corus (метка news). Используются, например, для эмбедингов https://github.com/natasha/navec . Я подумал, что было бы здорово дополнить тем, что собрано у вас.

**Comment by vtrokhymenko** [comment]
@iggisv9t что скажешь?
доброе дело делают товарищи, давай поможем нашими данными

**Comment by iggisv9t** [comment]
Конечно поможем. Конкретно тот источник данных пропал, так как его один из участников проекта добровольно хостил на своём гуглоакаунте и его там забанили по какой-то причине. Мы сейчас собираем всё снова в одном месте.

**Comment by kuk** [comment]
Ясно, спасибо, буду следить за обновлениями.

**Comment by iggisv9t** [comment]
Сделал релиз с нашими датасетами. Кроме коммерсанта, который надо заново скачивать.
https://github.com/ods-ai-ml4sg/proj_news_viz/releases/tag/data

**Comment by kuk** [comment]
👍

**Comment by kuk** [comment]
https://github.com/natasha/corus/commit/a5d71e96877fd5259473792dc0547700df0ed0d3
