### ISSUE TITLE
Make test failed

### ISSUE THREAD

**Issue by Ilseyar** [natasha/corus#51]
При запуске команды make test с оригинальным кодом из репозитория выдает ошибку:

> pytest \\
>         -vv --pep8 --flakes corus \\
>         --cov corus --cov-config setup.cfg \\
>         --cov-report term-missing --cov-report xml corus \\
>         --nbval-lax --current-env docs.ipynb  # repr spaces changes a bit in diff versions of ipython, so ignore output
> 
> ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> pytest: error: unrecognized arguments: --pep8 --cov corus --cov-config setup.cfg --cov-report term-missing --cov-report xml corus --nbval-lax --current-env docs.ipynb
>   inifile: /root/corus/corus/setup.cfg
>   rootdir: /root/corus/corus

> 
> Makefile:3: recipe for target 'test' failed
> make: *** [test] Error 4

Версия python: 3.5.2
Версия pytest: 6.1.1

**Comment by kuk** [comment]
Посмотрите в https://github.com/natasha/corus/blob/master/requirements/ci.txt, там нужно поставить плагины к pytest

**Comment by Ilseyar** [comment]
Спасибо, тесты прошли.
