### ISSUE TITLE
Dataset ERROR 404: Not Found

### ISSUE THREAD

**Issue by timurka** [natasha/corus#82]
Пробую:
!wget https://github.com/ods-ai-ml4sg/proj_news_viz/releases/download/data/meduza.csv.gz

Получаю:
--2022-12-10 15:15:57--  https://github.com/ods-ai-ml4sg/proj_news_viz/releases/download/data/meduza.csv.gz
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-10 15:15:58 ERROR 404: Not Found.

**Comment by kuk** [comment]
Боюсь что датасет не сохранился, у меня есть ссылки на два других новостых архива из этого проекта https://storage.yandexcloud.net/natasha-corus/ods/gazeta_v1.csv.zip и https://storage.yandexcloud.net/natasha-corus/ods/interfax_v1.csv.zip
